import Head from 'next/head'
import Image from 'next/image'
import Expression from '../components/Expression'
import styles from '../styles/Home.module.css'

const prod_1 = {
  operator: "product",
  operands: [
    { number: 2 }, 
    { variable: "a" }, 
    { variable: "b" }, 
    { variable: "c" }
  ]
}

const data = {
  operator: "product",
  operands: [
    { number: 2 }, 
    { variable: "a" }, 
    { variable: "b" }, 
    { variable: "c" }
  ]
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Expression expression={data}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
