import { DragDropContext, Droppable } from 'react-beautiful-dnd'

import Head from 'next/head'
import Image from 'next/image'
import Expression from '../components/Expression'
import styles from '../styles/Home.module.css'

const prod_1 = {
  operator: "product",
  operands: [
    { number: 2 }, 
    { variable: "a" }, 
    { variable: "b" }, 
    { variable: "c" }
  ]
}

const prod_2 = {
  operator: "product",
  operands: [{ variable:"x" }, { variable: "y"}]
}

const quot_1 = {
  operator: "quotient",
  operands: {
    numerator: { number: 1 },
    denominator: prod_2
  }
}

const exp_1 = {
  operator: "exponent",
  operands: {
    base: { variable: "e" },
    exponent: { variable: "x" }
  }
}

const data = {
  operator: "sum",
  operands: [
    prod_1, {variable: "x"}, quot_1, prod_2, exp_1
  ]
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} >
        <DragDropContext>
          <Droppable droppableId="symbols">
            {
              (provided) => (
              <ul 
                style={{fontSize:"4em"}}
                { ...provided.droppableProps }
                ref={provided.innerRef}
              >
              
                <Expression expression={data}/>

              </ul>
              )
            }
          </Droppable>
          
        </DragDropContext>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
